# # Visit https://golangci-lint.run/ for usage documentation
# # and information on other useful linters
# issues:
#   max-per-linter: 0
#   max-same-issues: 0

# linters:
#   disable-all: true
#   enable:
#     - durationcheck
#     - errcheck
#     - exportloopref
#     - forcetypeassert
#     - godot
#     - gofmt
#     - gosimple
#     - ineffassign
#     - makezero
#     - misspell
#     - nilerr
#     - predeclared
#     - staticcheck
#     - tenv
#     - unconvert
#     - unparam
#     - unused
#     - vet



# GolangCI-Lint configuration file.
# Visit https://golangci-lint.run/usage/configuration for details.

run:
  # Skip common directories that might contain generated or vendor code.
  skip-dirs:
    - vendor
    - generated
    - .git
  # Set a reasonable timeout to avoid hanging on large codebases.
  timeout: 5m

issues:
  max-per-linter: 0
  max-same-issues: 0
  # Optionally, add patterns here to ignore known or acceptable issues.
  exclude:
    # Example: ignore errors related to missing comments on exported functions.
    - "should have comment"
    # Add more patterns as needed

linters:
  disable-all: true
  enable:
    - durationcheck
    - errcheck
    - copyloopvar    # replaced exportloopref
    - forcetypeassert
    - godot
    - gofmt
    - gosimple
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - usetesting     # replaced tenv
    - unconvert
    - unparam
    - unused
    - govet          # replaced vet
