# .goreleaser.yml
project_name: "terraform-provider-cloudlab"

builds:
  - id: cloudlab
    main: ./main.go
    binary: "terraform-provider-cloudlab_{{.Version}}"
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
      - 386
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - id: release
    builds:
      - cloudlab
    format: zip
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

# If you don't want GPG signing, remove or comment out the 'signs:' block
