# sudo apt install docker
# sudo apt install docker-compose 
# sudo docker compose up --build or sudo docker-compose up --build
#Added firebase_admin 
version: '3'
services:
  web:
    image: python:3.8
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    working_dir: /app
    environment:
      - FLASK_ENV=production
    command: bash -c "
      pip install --upgrade pip &&
      pip install flask gunicorn &&  
      gunicorn -b 0.0.0.0:8080 --timeout 120 server:app"

