name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the repo
      - uses: actions/checkout@v3
        with:
          # Allow GoReleaser to access older tags for proper semver info.
          fetch-depth: 0

      # 2. Set up Go
      - uses: actions/setup-go@v4
        with:
          # This ensures we use the version in go.mod, so you don’t have to hardcode it here.
          go-version-file: 'go.mod'
          cache: true

     
      # 3. Run GoReleaser
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5.0.0
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Pass the GPG fingerprint to GoReleaser if you’re signing.
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
